name: Build and Test
on:
  pull_request:

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: "npm"
          registry-url: "https://registry.npmjs.org"

      - name: NPM install
        run: npm ci

      - name: Test
        run: npm run test

      - name: Compile
        run: npm run compile

      - name: Lint
        run: npm run lint
